Postgres and mail added
ViollaM/converty pull request #11
Opened 2023-06-12 19:12 UTC by hexangel1

2023-06-12 19:38 UTC, ViollaM requested changes

2023-06-12 19:38 UTC, ViollaM commented on Dockerfile
> +RUN pip install pyfiglet
Можешь эти зависимости в пипфайл добавить?

2023-06-12 19:38 UTC, ViollaM commented on source/telegram_bot.py
> +    if len(text) < 2:
Я бы сказала, тут надо != 1 и > 3, если флаг отправки на почту занимает одно слово, а если больше, то не 3, а нужную цифру

2023-06-12 19:38 UTC, ViollaM commented on source/telegram_bot.py
> +        print(f'Exception caught: {_ex}', flush=True)
Это наверное не надо?

2023-06-12 19:38 UTC, ViollaM commented on source/telegram_bot.py
> +    """Make feedback about bot"""
Надо поменять

2023-06-12 19:38 UTC, ViollaM commented on source/telegram_bot.py
> +        await msg.answer(_("Email updated!"))
```suggestion
        await msg.answer(_("Email send!"))
```

2023-06-12 19:38 UTC, ViollaM commented on source/telegram_bot.py
> +async def handle_lang(msg: types.Message):
handle_lang уже есть у нас

2023-06-12 19:38 UTC, ViollaM commented on source/telegram_bot.py
> +async def handle_lang(msg: types.Message):
handle_lang уже есть у нас

2023-06-12 19:39 UTC, ViollaM commented
еще надо локализацию для новых команд добавить

2023-06-12 19:40 UTC, hexangel1 commented on source/telegram_bot.py
> +async def handle_lang(msg: types.Message):
Исправлено!

2023-06-12 19:40 UTC, hexangel1 commented on source/telegram_bot.py
> +async def handle_lang(msg: types.Message):
Исправлено!

2023-06-12 19:42 UTC, hexangel1 commented on source/telegram_bot.py
> +        await msg.answer(_("Email updated!"))
Здесь именно updated

2023-06-12 19:42 UTC, hexangel1 commented on source/telegram_bot.py
> +    """Make feedback about bot"""
Исправлено!

2023-06-12 19:42 UTC, hexangel1 commented on source/telegram_bot.py
> +        print(f'Exception caught: {_ex}', flush=True)
Для отладки думаю лишним не будет, мне помогало

2023-06-12 19:44 UTC, hexangel1 commented on source/telegram_bot.py
> +    if len(text) < 2:
Исправлено!

2023-06-12 19:47 UTC, hexangel1 commented on Dockerfile
> +RUN pip install pyfiglet
Добавил

2023-06-13 08:57 UTC, ViollaM requested changes

2023-06-13 08:57 UTC, ViollaM commented on locales/en/LC_MESSAGES/converty.po
> -"/help <command> to see additional information about chosen command\n"
вот это удалять не надо, надо добавить новые строки

2023-06-13 08:57 UTC, ViollaM commented on locales/en/LC_MESSAGES/converty.po
> +#~ "/help <command> to see additional information about chosen command\n"
вот это зачем закомментированное тут?

2023-06-13 08:57 UTC, ViollaM commented on locales/fr/LC_MESSAGES/converty.po
> -"commande choisie\n"
аналогично как для англа

2023-06-13 08:57 UTC, ViollaM commented on locales/fr/LC_MESSAGES/converty.po
> +#~ " choisie\n"
аналогично

2023-06-13 08:57 UTC, ViollaM commented on locales/ru/LC_MESSAGES/converty.po
> -"команде\n"
аналогично

2023-06-13 08:57 UTC, ViollaM commented on locales/ru/LC_MESSAGES/converty.po
> +#~ " информацию о выбранной команде\n"
аналогично

2023-06-13 09:32 UTC, ViollaM commented on source/telegram_bot.py
> +bot = Bot(token=config["Converty"]["SecretToken"])
Можешь пожалуйста тут какие-то заглуши поставить, чтобы все компилировалось, если нет таких полей в конфиге?

2023-06-13 10:04 UTC, hexangel1 commented on source/telegram_bot.py
> +bot = Bot(token=config["Converty"]["SecretToken"])
без секрет токена все равно работать не будет

2023-06-13 10:23 UTC, hexangel1 commented on locales/en/LC_MESSAGES/converty.po
> +#~ "/help <command> to see additional information about chosen command\n"
Удалено

2023-06-13 10:23 UTC, hexangel1 commented on locales/fr/LC_MESSAGES/converty.po
> -"commande choisie\n"
Сделан перевод!

2023-06-13 10:23 UTC, hexangel1 commented on locales/fr/LC_MESSAGES/converty.po
> +#~ " choisie\n"
Удалено!

2023-06-13 10:23 UTC, hexangel1 commented on locales/ru/LC_MESSAGES/converty.po
> -"команде\n"
Сделан перевод!

2023-06-13 10:23 UTC, hexangel1 commented on locales/ru/LC_MESSAGES/converty.po
> +#~ " информацию о выбранной команде\n"
Удалено!

2023-06-13 10:25 UTC, hexangel1 commented
> еще надо локализацию для новых команд добавить
Добавил локализацию новых команд

2023-06-13 10:33 UTC, ViollaM approved these changes

2023-06-13 10:33 UTC, merged